// auto-generated by build_site.py
window.PERTH_PLACES = [
 {
  "slug": "kings-park",
  "name": "Kings Park",
  "lat": -31.96,
  "lon": 115.831,
  "cat": "park",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "One of the world's largest inner-city parks, rising above the Swan River with sweeping views of the skyline.",
  "hl": [
   "Botanic Garden of WA native plants",
   "War Memorial & State War Memorial precinct",
   "Lotterywest Federation Walkway treetop bridge"
  ],
  "tip": "Free entry, open daily. Best at sunset or during the spring wildflower festival (Sept)."
 },
 {
  "slug": "elizabeth-quay",
  "name": "Elizabeth Quay",
  "lat": -31.959,
  "lon": 115.858,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "A riverside dining and events precinct wrapped around an inlet, linked by a striking pedestrian bridge.",
  "hl": [
   "BHP Water Park for kids",
   "Bars, restaurants & the Ferris wheel",
   "Ferry to South Perth Zoo"
  ],
  "tip": "Great in the evening; markets and events on weekends."
 },
 {
  "slug": "bell-tower",
  "name": "The Bell Tower",
  "lat": -31.96,
  "lon": 115.861,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "A copper-and-glass spire on the waterfront housing the historic bells of St Martin-in-the-Fields, London.",
  "hl": [
   "Ring the bells yourself",
   "360° observation deck",
   "Riverside location by Elizabeth Quay"
  ],
  "tip": "Small entry fee; bell-ringing demos daily."
 },
 {
  "slug": "perth-mint",
  "name": "The Perth Mint",
  "lat": -31.958,
  "lon": 115.869,
  "cat": "historic",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "Australia's oldest operating mint (1899), where you can watch a gold pour and see a giant one-tonne gold coin.",
  "hl": [
   "Live gold pour demonstration",
   "World's largest coin (1 tonne)",
   "Historic 1899 limestone building"
  ],
  "tip": "Ticketed tours run through the day."
 },
 {
  "slug": "wa-museum",
  "name": "WA Museum Boola Bardip",
  "lat": -31.947,
  "lon": 115.86,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "The state museum reborn — 'Boola Bardip' means 'many stories' in Noongar — spanning WA's people, land and wildlife.",
  "hl": [
   "Blue whale skeleton",
   "Aboriginal culture galleries",
   "Free general entry"
  ],
  "tip": "Free general admission; special exhibitions ticketed."
 },
 {
  "slug": "art-gallery-wa",
  "name": "Art Gallery of WA",
  "lat": -31.949,
  "lon": 115.862,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "The state's premier art collection, from Aboriginal art to Australian and international works, in the Perth Cultural Centre.",
  "hl": [
   "State Art Collection",
   "Rooftop bar with city views",
   "Free general entry"
  ],
  "tip": "Free general admission."
 },
 {
  "slug": "state-buildings",
  "name": "State Buildings",
  "lat": -31.954,
  "lon": 115.86,
  "cat": "historic",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "Beautifully restored 19th-century government buildings now home to COMO The Treasury hotel, bars and restaurants.",
  "hl": [
   "Wildflower & Petition dining",
   "Grand heritage architecture",
   "Long Chim & Post laneway bars"
  ],
  "tip": "Free to wander the arcades; dining bookings advised."
 },
 {
  "slug": "supreme-court-gardens",
  "name": "Supreme Court Gardens",
  "lat": -31.958,
  "lon": 115.864,
  "cat": "park",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "A shady riverside lawn and gardens in the heart of the city, a favourite for summer concerts and picnics.",
  "hl": [
   "Heritage fig trees",
   "Summer concert venue",
   "Steps from the river"
  ],
  "tip": "Free, open space; big events in summer."
 },
 {
  "slug": "northbridge",
  "name": "Northbridge",
  "lat": -31.947,
  "lon": 115.853,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "Perth's nightlife and food heartland just north of the railway, packed with restaurants, bars and galleries.",
  "hl": [
   "Chinatown & James St dining",
   "Yagan Square & the markets",
   "Bars and live music"
  ],
  "tip": "Liveliest in the evening; very multicultural food scene."
 },
 {
  "slug": "watertown",
  "name": "Watertown Brand Outlet",
  "lat": -31.95,
  "lon": 115.842,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "A large outlet shopping centre on the western edge of the CBD with discount brand stores.",
  "hl": [
   "Discount fashion & brands",
   "Easy CBD access",
   "Undercover shopping"
  ],
  "tip": "Open daily; a rainy-day option."
 },
 {
  "slug": "c-restaurant",
  "name": "C Restaurant",
  "lat": -31.953,
  "lon": 115.856,
  "cat": "food",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "Perth's revolving restaurant, high in St Martins Tower, turning a full circle for 360° city and river views.",
  "hl": [
   "Slowly revolving dining room",
   "Panoramic city views",
   "Fine-dining menu"
  ],
  "tip": "Bookings essential; best at dusk."
 },
 {
  "slug": "point-fraser",
  "name": "Point Fraser",
  "lat": -31.96,
  "lon": 115.873,
  "cat": "park",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "An East Perth foreshore reserve with wetlands, a boardwalk and cafe right on the Swan River.",
  "hl": [
   "Riverside boardwalk & wetlands",
   "Cafe and picnic lawns",
   "Views across to South Perth"
  ],
  "tip": "Free; lovely for a morning walk."
 },
 {
  "slug": "waca",
  "name": "WACA Ground",
  "lat": -31.958,
  "lon": 115.879,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "The historic Western Australian Cricket Association ground, a legendary Test venue with a cricket museum.",
  "hl": [
   "Historic cricket Test ground",
   "WACA museum",
   "East Perth location"
  ],
  "tip": "Museum & tours on selected days."
 },
 {
  "slug": "optus-stadium",
  "name": "Optus Stadium",
  "lat": -31.951,
  "lon": 115.889,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "Perth's world-class 60,000-seat stadium at Burswood, home to AFL and cricket, ringed by parkland and a riverside plaza.",
  "hl": [
   "AFL, cricket & concerts",
   "Matagarup Bridge & zip-line",
   "Riverside Chevron Parkland"
  ],
  "tip": "Event days only for inside; parkland open always."
 },
 {
  "slug": "crown-perth",
  "name": "Crown Perth",
  "lat": -31.96,
  "lon": 115.891,
  "cat": "attraction",
  "region": "Perth CBD",
  "approx": false,
  "blurb": "A large entertainment complex at Burswood with a casino, hotels, restaurants and a theatre.",
  "hl": [
   "Casino & Crown Towers hotel",
   "Riverside restaurants",
   "Live shows & events"
  ],
  "tip": "18+ for the casino; dining open to all."
 },
 {
  "slug": "two-rocks",
  "name": "Two Rocks",
  "lat": -31.512,
  "lon": 115.588,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "A laid-back northern coastal town with a marina, fishing and the quirky King Neptune statues at Atlantis.",
  "hl": [
   "Two Rocks Marina",
   "Fishing & boating",
   "Atlantis Marine Park ruins"
  ],
  "tip": "Quiet; good for a long drive north up the coast."
 },
 {
  "slug": "yanchep",
  "name": "Yanchep National Park",
  "lat": -31.548,
  "lon": 115.688,
  "cat": "park",
  "region": "North Coast",
  "approx": false,
  "blurb": "A national park famous for its koala boardwalk, caves, wetlands and Noongar heritage, just north of Perth.",
  "hl": [
   "Koala boardwalk",
   "Crystal Cave tours",
   "Loch McNess & walk trails"
  ],
  "tip": "Park entry fee applies; cave tours ticketed."
 },
 {
  "slug": "burns-beach",
  "name": "Burns Beach",
  "lat": -31.723,
  "lon": 115.717,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "A relaxed northern beach suburb with a coastal path, cafe and reef for snorkelling.",
  "hl": [
   "Beachfront cafe",
   "Coastal walk to Iluka",
   "Snorkelling on the reef"
  ],
  "tip": "Free parking; family-friendly."
 },
 {
  "slug": "mullaloo",
  "name": "Mullaloo Beach",
  "lat": -31.777,
  "lon": 115.732,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "A wide, calm family beach with grassed foreshore, playground and a popular beachfront tavern.",
  "hl": [
   "Gentle swimming beach",
   "Playground & BBQs",
   "Mullaloo Beach Hotel"
  ],
  "tip": "Patrolled in summer; great for kids."
 },
 {
  "slug": "hillarys",
  "name": "Hillarys Boat Harbour",
  "lat": -31.822,
  "lon": 115.735,
  "cat": "attraction",
  "region": "North Coast",
  "approx": false,
  "blurb": "A bustling marina village with a sheltered swimming beach, restaurants, and the AQWA aquarium.",
  "hl": [
   "AQWA — Aquarium of WA",
   "Sorrento Quay dining & shops",
   "Ferry to Rottnest Island"
  ],
  "tip": "Free to wander; AQWA & ferries ticketed. Includes AQWA & Sorrento Quay."
 },
 {
  "slug": "trigg",
  "name": "Trigg Beach",
  "lat": -31.867,
  "lon": 115.755,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "Perth's premier surf beach, with a rocky point, cafe and consistent waves.",
  "hl": [
   "Best surf near the city",
   "Bathers Beach cafe",
   "Rockpools at low tide"
  ],
  "tip": "Strong currents — swim between the flags."
 },
 {
  "slug": "scarborough",
  "name": "Scarborough Beach",
  "lat": -31.894,
  "lon": 115.756,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "A revitalised beachfront with a huge pool, skate park, amphitheatre and lively bar/restaurant strip.",
  "hl": [
   "Scarborough Beach Pool",
   "Esplanade bars & eateries",
   "Surfing & sunset views"
  ],
  "tip": "Free foreshore; busy on summer evenings."
 },
 {
  "slug": "city-beach",
  "name": "City Beach",
  "lat": -31.935,
  "lon": 115.752,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "A broad, family-friendly beach with grassed terraces and upmarket beachfront dining.",
  "hl": [
   "Wide swimming beach",
   "Clancy's & Odyssea dining",
   "Grassed picnic terraces"
  ],
  "tip": "Patrolled; good parking."
 },
 {
  "slug": "cottesloe",
  "name": "Cottesloe Beach",
  "lat": -31.996,
  "lon": 115.751,
  "cat": "beach",
  "region": "North Coast",
  "approx": false,
  "blurb": "Perth's iconic beach — golden sand, Norfolk pines, the Indiana teahouse and famous sunsets.",
  "hl": [
   "Sculpture by the Sea (March)",
   "Indiana teahouse",
   "Great swimming & snorkelling"
  ],
  "tip": "Iconic at sunset; arrive early on hot days."
 },
 {
  "slug": "joondalup",
  "name": "Joondalup",
  "lat": -31.744,
  "lon": 115.766,
  "cat": "suburb",
  "region": "Northern Suburbs",
  "approx": false,
  "blurb": "The bustling centre of Perth's northern suburbs, built around Lake Joondalup with a lively city core.",
  "hl": [
   "Lakeside Joondalup shopping",
   "Central business & dining hub",
   "Yellagonga Regional Park lakes"
  ],
  "tip": "Train terminus of the Joondalup line."
 },
 {
  "slug": "joondalup-market",
  "name": "Joondalup Markets",
  "lat": -31.746,
  "lon": 115.772,
  "cat": "food",
  "region": "Northern Suburbs",
  "approx": true,
  "blurb": "Weekend and twilight markets in Joondalup with fresh produce, street food and local stalls.",
  "hl": [
   "Fresh produce & street food",
   "Local craft stalls",
   "Family atmosphere"
  ],
  "tip": "Check days/times before visiting — seasonal."
 },
 {
  "slug": "whiteman-park",
  "name": "Whiteman Park",
  "lat": -31.833,
  "lon": 115.945,
  "cat": "park",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A huge bushland park on the edge of the Swan Valley with wildlife, heritage trams, trains and playgrounds.",
  "hl": [
   "Caversham Wildlife Park inside",
   "Heritage tram & train rides",
   "Village, cafes & playgrounds"
  ],
  "tip": "Free entry to the park; some attractions ticketed."
 },
 {
  "slug": "caversham",
  "name": "Caversham Wildlife Park",
  "lat": -31.87,
  "lon": 115.955,
  "cat": "attraction",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "One of WA's best hands-on wildlife parks, inside Whiteman Park — cuddle koalas and hand-feed kangaroos.",
  "hl": [
   "Hold a koala & feed roos",
   "Farm show & wombats",
   "Huge native animal collection"
  ],
  "tip": "Ticketed; allow half a day."
 },
 {
  "slug": "sandalford",
  "name": "Sandalford Wines",
  "lat": -31.878,
  "lon": 115.958,
  "cat": "food",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A grand, historic Swan Valley winery (est. 1840) known for its cellar door, restaurant and summer concerts.",
  "hl": [
   "Cellar door tastings",
   "Estate restaurant",
   "Big-name summer concerts"
  ],
  "tip": "Tastings & dining daily; concerts ticketed."
 },
 {
  "slug": "sittella",
  "name": "Sittella Winery",
  "lat": -31.805,
  "lon": 116.02,
  "cat": "food",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A family-owned Herne Hill winery with an award-winning restaurant and valley views.",
  "hl": [
   "Award-winning restaurant",
   "Sparkling & table wines",
   "Vineyard views"
  ],
  "tip": "Lunch bookings recommended."
 },
 {
  "slug": "sacred-india-gallery",
  "name": "Sacred India Gallery",
  "lat": -31.795,
  "lon": 115.985,
  "cat": "attraction",
  "region": "Swan Valley",
  "approx": true,
  "blurb": "A tranquil gallery and Indian-inspired garden in the Swan Valley, with artworks, statues and a cafe.",
  "hl": [
   "Indian art & antiques",
   "Peaceful sculpture gardens",
   "Cafe on site"
  ],
  "tip": "Small entry/donation; check opening days."
 },
 {
  "slug": "ellenbrook",
  "name": "Ellenbrook",
  "lat": -31.775,
  "lon": 115.985,
  "cat": "suburb",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A large master-planned town on the Swan Valley's edge, with a town centre, parks and the new Ellenbrook rail line.",
  "hl": [
   "Ellenbrook Central shopping",
   "Parks & lakes",
   "Gateway to the Swan Valley"
  ],
  "tip": "Handy base for exploring the valley."
 },
 {
  "slug": "bailey-brewing",
  "name": "Bailey Brewing Co",
  "lat": -31.83,
  "lon": 116.0,
  "cat": "food",
  "region": "Swan Valley",
  "approx": true,
  "blurb": "A Swan Valley craft brewery pouring house-made beers with relaxed food and family-friendly grounds.",
  "hl": [
   "House-brewed craft beer",
   "Relaxed beer garden",
   "Wood-fired food"
  ],
  "tip": "Great weekend stop on the brewery trail."
 },
 {
  "slug": "aurelien",
  "name": "Aurelien",
  "lat": -31.81,
  "lon": 116.0,
  "cat": "food",
  "region": "Swan Valley",
  "approx": true,
  "blurb": "A Swan Valley dining destination among the vines, part of the region's celebrated food and wine trail.",
  "hl": [
   "Seasonal produce menu",
   "Vineyard surrounds",
   "Swan Valley food trail"
  ],
  "tip": "Bookings advised."
 },
 {
  "slug": "seven-sins",
  "name": "Seven Sins",
  "lat": -31.84,
  "lon": 115.99,
  "cat": "food",
  "region": "Swan Valley",
  "approx": true,
  "blurb": "A Swan Valley cellar door / eatery leaning into indulgence — wine, sweets and long lazy lunches.",
  "hl": [
   "Wine tastings",
   "Chocolates & treats",
   "Relaxed valley vibe"
  ],
  "tip": "One for a leisurely afternoon."
 },
 {
  "slug": "avocado-grove",
  "name": "The Avocado Grove",
  "lat": -31.82,
  "lon": 116.01,
  "cat": "food",
  "region": "Swan Valley",
  "approx": true,
  "blurb": "A Swan Valley grove and cafe celebrating local produce, with orchard views and farm-fresh fare.",
  "hl": [
   "Farm-fresh cafe fare",
   "Orchard setting",
   "Local produce to buy"
  ],
  "tip": "Seasonal — check opening days."
 },
 {
  "slug": "guildford",
  "name": "Guildford",
  "lat": -31.9,
  "lon": 115.973,
  "cat": "historic",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A historic river town at the gateway to the Swan Valley, full of heritage buildings, antiques and old pubs.",
  "hl": [
   "Heritage main street",
   "Antique & vintage shops",
   "Historic Guildford Hotel"
  ],
  "tip": "Free to explore; markets on some weekends."
 },
 {
  "slug": "midland",
  "name": "Midland",
  "lat": -31.888,
  "lon": 116.01,
  "cat": "historic",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A regional hub built on the old railway workshops, now a heritage precinct with markets and shopping.",
  "hl": [
   "Midland Railway Workshops heritage",
   "Weekend markets",
   "Regional shopping centre"
  ],
  "tip": "Heritage tours of the workshops on some days."
 },
 {
  "slug": "bells-rapids",
  "name": "Bells Rapids",
  "lat": -31.774,
  "lon": 116.045,
  "cat": "park",
  "region": "Swan Valley",
  "approx": false,
  "blurb": "A scenic reserve where the Swan and Avon rivers meet — bushwalks, granite and the Avon Descent finish nearby.",
  "hl": [
   "Swan River walk trails",
   "Granite outcrops & rapids",
   "Avon Descent viewing (Aug)"
  ],
  "tip": "Free; wear sturdy shoes for the trails."
 },
 {
  "slug": "john-forrest-np",
  "name": "John Forrest National Park",
  "lat": -31.885,
  "lon": 116.088,
  "cat": "park",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "WA's oldest national park, with waterfalls, a heritage railway tunnel walk and a hilltop tavern.",
  "hl": [
   "National Park Falls",
   "Railway Reserves Heritage Trail",
   "John Forrest Tavern"
  ],
  "tip": "Park entry fee; waterfalls best in winter/spring."
 },
 {
  "slug": "lake-leschenaultia",
  "name": "Lake Leschenaultia",
  "lat": -31.878,
  "lon": 116.213,
  "cat": "park",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A tranquil man-made lake at Chidlow for swimming, canoeing and camping among the jarrah forest.",
  "hl": [
   "Swimming & canoe hire",
   "Lakeside camping",
   "Bushwalk & bike trails"
  ],
  "tip": "Small entry fee; canoe hire seasonal."
 },
 {
  "slug": "mundaring",
  "name": "Mundaring",
  "lat": -31.9,
  "lon": 116.167,
  "cat": "hills",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A leafy hills town, a hub for the surrounding forest, trails and the historic Mundaring Weir.",
  "hl": [
   "Village shops & cafes",
   "Gateway to hills trails",
   "Sculpture park nearby"
  ],
  "tip": "Nice base for a hills day trip."
 },
 {
  "slug": "mundaring-weir",
  "name": "Mundaring Weir",
  "lat": -31.96,
  "lon": 116.17,
  "cat": "attraction",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A historic dam that pumps water 560 km to Kalgoorlie's goldfields — an engineering marvel with a hotel and museum.",
  "hl": [
   "Historic C.Y. O'Connor pipeline",
   "Weir wall & lookout",
   "Mundaring Weir Hotel"
  ],
  "tip": "Free to view; museum & hotel nearby."
 },
 {
  "slug": "kalamunda",
  "name": "Kalamunda",
  "lat": -31.976,
  "lon": 116.058,
  "cat": "hills",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A charming hills town with a history village, weekend markets, and the start of the Bibbulmun Track.",
  "hl": [
   "Kalamunda History Village",
   "Saturday markets",
   "Bibbulmun Track northern end"
  ],
  "tip": "Includes nearby Lesmurdie Falls. Markets Saturday mornings."
 },
 {
  "slug": "lesmurdie",
  "name": "Lesmurdie Falls",
  "lat": -31.995,
  "lon": 116.055,
  "cat": "park",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A hills suburb best known for Lesmurdie Falls, which tumble down the Darling Scarp with valley views.",
  "hl": [
   "Lesmurdie Falls walk",
   "Coastal-plain views",
   "Foothills bushland"
  ],
  "tip": "Free; falls flow best after winter rain."
 },
 {
  "slug": "carmel",
  "name": "Carmel",
  "lat": -32.02,
  "lon": 116.085,
  "cat": "suburb",
  "region": "Perth Hills",
  "approx": true,
  "blurb": "A quiet rural-residential pocket of the Perth Hills among orchards and bushland.",
  "hl": [
   "Orchards & small farms",
   "Bushland surrounds",
   "Peaceful drive"
  ],
  "tip": "Rural; combine with Pickering Brook wineries."
 },
 {
  "slug": "pickering-brook",
  "name": "Pickering Brook",
  "lat": -32.03,
  "lon": 116.1,
  "cat": "suburb",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A hills orchard district known for apples, cider and cherry season, with cellar doors and farm gates.",
  "hl": [
   "Apple & cherry orchards",
   "Cider houses",
   "Autumn harvest season"
  ],
  "tip": "Best in autumn (cherries early summer)."
 },
 {
  "slug": "core-cider",
  "name": "Core Cider House",
  "lat": -32.025,
  "lon": 116.1,
  "cat": "food",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A Pickering Brook orchard and cider house making apple cider from its own trees, with tastings and meals.",
  "hl": [
   "Apple cider tastings",
   "Orchard views",
   "Family-friendly meals"
  ],
  "tip": "Cellar door daily; lunch on weekends."
 },
 {
  "slug": "lavender-bistro",
  "name": "Lavender Bistro",
  "lat": -32.02,
  "lon": 116.11,
  "cat": "food",
  "region": "Perth Hills",
  "approx": true,
  "blurb": "A relaxed Perth Hills eatery among the trees, popular for long lunches and country-style fare.",
  "hl": [
   "Country-style dining",
   "Garden setting",
   "Seasonal menu"
  ],
  "tip": "Bookings advised on weekends."
 },
 {
  "slug": "bickley-valley",
  "name": "Bickley Valley",
  "lat": -32.022,
  "lon": 116.098,
  "cat": "hills",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A pretty hills valley of wineries, orchards and observatories, ideal for a slow food-and-wine wander.",
  "hl": [
   "Boutique wineries",
   "Perth Observatory nearby",
   "Orchard scenery"
  ],
  "tip": "Cellar doors mostly open weekends."
 },
 {
  "slug": "roleystone",
  "name": "Roleystone",
  "lat": -32.115,
  "lon": 116.072,
  "cat": "park",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A forested hills suburb wrapped around Araluen Botanic Park and the Canning River gorge.",
  "hl": [
   "Araluen Botanic Park",
   "Tulip festival (spring)",
   "Canning River & dam"
  ],
  "tip": "Includes Araluen Botanic Park (ticketed)."
 },
 {
  "slug": "jarrahdale",
  "name": "Jarrahdale",
  "lat": -32.335,
  "lon": 116.06,
  "cat": "historic",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A historic timber-milling village in the jarrah forest, with heritage cottages, walk trails and a tavern.",
  "hl": [
   "Heritage timber-town buildings",
   "Serpentine forest trails",
   "Millbrook Winery nearby"
  ],
  "tip": "Free to explore; great autumn colours."
 },
 {
  "slug": "millbrook-winery",
  "name": "Millbrook Winery",
  "lat": -32.355,
  "lon": 116.055,
  "cat": "food",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A picturesque estate winery near Jarrahdale with a lauded restaurant overlooking the dam and gardens.",
  "hl": [
   "Estate restaurant",
   "Lakeside cellar door",
   "Kitchen garden produce"
  ],
  "tip": "Lunch bookings essential; scenic drive."
 },
 {
  "slug": "serpentine-falls",
  "name": "Serpentine Falls",
  "lat": -32.362,
  "lon": 116.01,
  "cat": "park",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A popular waterfall and swimming hole in Serpentine National Park, with kangaroos and forest trails.",
  "hl": [
   "Waterfall & swimming pool",
   "Resident kangaroos",
   "Forest walk trails"
  ],
  "tip": "Park entry fee; can reach capacity on hot days."
 },
 {
  "slug": "secret-garden",
  "name": "Secret Garden",
  "lat": -32.34,
  "lon": 116.0,
  "cat": "attraction",
  "region": "Perth Hills",
  "approx": true,
  "blurb": "A tucked-away garden retreat on the edge of the hills — greenery, quiet paths and a relaxed cafe.",
  "hl": [
   "Landscaped gardens",
   "Peaceful cafe",
   "Photo-worthy corners"
  ],
  "tip": "Check opening days before visiting."
 },
 {
  "slug": "south-perth",
  "name": "South Perth Foreshore",
  "lat": -31.977,
  "lon": 115.853,
  "cat": "attraction",
  "region": "South of River",
  "approx": false,
  "blurb": "A riverside foreshore with the best postcard view of the Perth skyline, plus Perth Zoo just behind.",
  "hl": [
   "Best city skyline view",
   "Perth Zoo nearby",
   "Ferry to Elizabeth Quay"
  ],
  "tip": "Includes Perth Zoo & the foreshore. Free foreshore; zoo ticketed."
 },
 {
  "slug": "applecross",
  "name": "Applecross",
  "lat": -32.015,
  "lon": 115.835,
  "cat": "suburb",
  "region": "South of River",
  "approx": false,
  "blurb": "A leafy riverside suburb with a village strip, jetty and the landmark Raffles hotel on the water.",
  "hl": [
   "Riverside walk & jetty",
   "Ardross St cafe strip",
   "Canning Bridge views"
  ],
  "tip": "Lovely for a riverside stroll."
 },
 {
  "slug": "point-walter",
  "name": "Point Walter",
  "lat": -32.02,
  "lon": 115.788,
  "cat": "park",
  "region": "South of River",
  "approx": false,
  "blurb": "A Swan River reserve with a long sandbar (spit), grassy picnic areas and calm swimming.",
  "hl": [
   "Walk out on the sandbar",
   "Picnics & BBQs",
   "Calm river swimming"
  ],
  "tip": "Free; sandbar best at low tide."
 },
 {
  "slug": "wireless-hill",
  "name": "Wireless Hill Park",
  "lat": -32.03,
  "lon": 115.828,
  "cat": "park",
  "region": "South of River",
  "approx": false,
  "blurb": "A bushland hilltop park on a historic radio-telegraph site, superb for wildflowers and city views.",
  "hl": [
   "Spring wildflowers",
   "Telecommunications museum",
   "Panoramic views"
  ],
  "tip": "Free; wildflowers peak Sept–Oct."
 },
 {
  "slug": "nedlands",
  "name": "Nedlands",
  "lat": -31.98,
  "lon": 115.81,
  "cat": "suburb",
  "region": "South of River",
  "approx": false,
  "blurb": "An affluent riverside suburb near UWA, with foreshore parks, jetties and the Captain Stirling strip.",
  "hl": [
   "Swan River foreshore",
   "Near UWA & QEII",
   "Riverside dining"
  ],
  "tip": "Pleasant riverside walks."
 },
 {
  "slug": "peppermint-grove",
  "name": "Peppermint Grove",
  "lat": -32.0,
  "lon": 115.77,
  "cat": "suburb",
  "region": "South of River",
  "approx": false,
  "blurb": "WA's smallest and most exclusive suburb, a green riverside enclave of grand homes near the water.",
  "hl": [
   "Leafy heritage streets",
   "Manning Park & jetty",
   "Near Cottesloe"
  ],
  "tip": "A quiet, scenic drive-through."
 },
 {
  "slug": "fremantle",
  "name": "Fremantle",
  "lat": -32.055,
  "lon": 115.748,
  "cat": "historic",
  "region": "South of River",
  "approx": false,
  "blurb": "Perth's historic port city — heritage streets, markets, breweries and a world-famous prison.",
  "hl": [
   "Fremantle Prison (UNESCO)",
   "Fremantle Markets",
   "The Round House & Fishing Boat Harbour"
  ],
  "tip": "Includes the Prison, Round House & Fishing Boat Harbour. Markets Fri–Sun."
 },
 {
  "slug": "coogee",
  "name": "Coogee Beach",
  "lat": -32.115,
  "lon": 115.762,
  "cat": "beach",
  "region": "South of River",
  "approx": false,
  "blurb": "A calm family beach south of Fremantle with a long jetty, the Omeo dive wreck and a grassed foreshore.",
  "hl": [
   "Omeo shipwreck snorkel trail",
   "Long swimming jetty",
   "Coogee Beach cafe"
  ],
  "tip": "Patrolled in summer; great for families."
 },
 {
  "slug": "bibra-lake",
  "name": "Bibra Lake",
  "lat": -32.098,
  "lon": 115.825,
  "cat": "park",
  "region": "South of River",
  "approx": false,
  "blurb": "A large wetland lake and regional park with a boardwalk, adventure playground and abundant birdlife.",
  "hl": [
   "Adventure playground",
   "Wetland boardwalk & birds",
   "Walk/cycle loop"
  ],
  "tip": "Free; big playground for kids."
 },
 {
  "slug": "aubin-grove",
  "name": "Aubin Grove",
  "lat": -32.16,
  "lon": 115.855,
  "cat": "suburb",
  "region": "South of River",
  "approx": true,
  "blurb": "A newer southern suburb with a train station on the Mandurah line and family parks.",
  "hl": [
   "Train station on Mandurah line",
   "Family parklands",
   "Handy southern base"
  ],
  "tip": "Park-and-ride hub for the south."
 },
 {
  "slug": "southern-river",
  "name": "Southern River",
  "lat": -32.1,
  "lon": 115.95,
  "cat": "suburb",
  "region": "South of River",
  "approx": true,
  "blurb": "A growing suburb of parks and wetlands in Perth's south-east, along the Southern River.",
  "hl": [
   "Wetlands & reserves",
   "Family neighbourhoods",
   "Close to Gosnells"
  ],
  "tip": "Quiet residential area."
 },
 {
  "slug": "harrisdale",
  "name": "Harrisdale",
  "lat": -32.115,
  "lon": 115.92,
  "cat": "suburb",
  "region": "South of River",
  "approx": true,
  "blurb": "A modern master-planned suburb in the south-east with parks, wetlands and Stockland Harrisdale.",
  "hl": [
   "Piara Waters wetlands nearby",
   "Local shopping",
   "New parklands"
  ],
  "tip": "Newer family suburb."
 },
 {
  "slug": "piara-waters",
  "name": "Piara Waters",
  "lat": -32.125,
  "lon": 115.915,
  "cat": "suburb",
  "region": "South of River",
  "approx": true,
  "blurb": "A fast-growing southern suburb next to Harrisdale, with fresh parks, schools and wetland reserves.",
  "hl": [
   "Wetland reserves",
   "Playgrounds & schools",
   "Modern estates"
  ],
  "tip": "Pairs with neighbouring Harrisdale."
 },
 {
  "slug": "rockingham",
  "name": "Rockingham",
  "lat": -32.278,
  "lon": 115.729,
  "cat": "hills",
  "region": "Southern Suburbs",
  "approx": false,
  "blurb": "A coastal city south of Perth with calm swimming beaches, a foreshore strip and wild dolphins offshore.",
  "hl": [
   "Calm swimming foreshore",
   "Dolphin & Penguin Island tours",
   "Waterfront dining"
  ],
  "tip": "Gateway to Penguin Island (ferry seasonal)."
 },
 {
  "slug": "baldivis",
  "name": "Baldivis",
  "lat": -32.33,
  "lon": 115.82,
  "cat": "suburb",
  "region": "Southern Suburbs",
  "approx": true,
  "blurb": "A rapidly growing suburb between Rockingham and the freeway, with big parks and the Baldivis Children's Forest.",
  "hl": [
   "Baldivis Children's Forest",
   "Stockland shopping",
   "Family parklands"
  ],
  "tip": "Handy stop off the Kwinana Freeway."
 },
 {
  "slug": "penguin-island",
  "name": "Penguin Island",
  "lat": -32.305,
  "lon": 115.69,
  "cat": "park",
  "region": "Southern Suburbs",
  "approx": false,
  "blurb": "A small island reserve off Rockingham, home to little penguins, sea lions and pelicans, reached by ferry.",
  "hl": [
   "Little penguin colony",
   "Boardwalks & beaches",
   "Sea lion & dolphin cruises"
  ],
  "tip": "Island closed June–mid Sept (nesting); ferry ticketed."
 },
 {
  "slug": "secret-harbour",
  "name": "Secret Harbour",
  "lat": -32.41,
  "lon": 115.76,
  "cat": "beach",
  "region": "Southern Suburbs",
  "approx": false,
  "blurb": "A surf-side southern suburb with a patrolled beach, surf club and a village shopping centre.",
  "hl": [
   "Patrolled surf beach",
   "Surf lifesaving club",
   "Beachside cafes"
  ],
  "tip": "Good surf; swim between the flags."
 },
 {
  "slug": "port-kennedy",
  "name": "Port Kennedy",
  "lat": -32.375,
  "lon": 115.755,
  "cat": "suburb",
  "region": "Southern Suburbs",
  "approx": true,
  "blurb": "A coastal suburb south of Rockingham with beaches, a golf resort and a scientific bushland park.",
  "hl": [
   "Long sandy beaches",
   "Golf & foreshore",
   "Port Kennedy bushland"
  ],
  "tip": "Quiet coastal drive."
 },
 {
  "slug": "mandurah",
  "name": "Mandurah",
  "lat": -32.528,
  "lon": 115.722,
  "cat": "hills",
  "region": "Peel Region",
  "approx": false,
  "blurb": "A relaxed waterway city an hour south of Perth, famous for its canals, dolphins, crabbing and foreshore.",
  "hl": [
   "Dolphin & canal cruises",
   "Blue-manna crabbing",
   "Mandurah Foreshore & markets"
  ],
  "tip": "End of the Mandurah rail line; great day trip."
 },
 {
  "slug": "pinjarra",
  "name": "Pinjarra",
  "lat": -32.63,
  "lon": 115.875,
  "cat": "hills",
  "region": "Peel Region",
  "approx": false,
  "blurb": "A historic town on the Murray River in the Peel region, with heritage buildings and a scenic steam railway.",
  "hl": [
   "Murray River picnic spots",
   "Hotham Valley steam train",
   "Country heritage town"
  ],
  "tip": "Combine with Edenvale Heritage Precinct."
 },
 {
  "slug": "edenvale-heritage",
  "name": "Edenvale Heritage Precinct",
  "lat": -32.628,
  "lon": 115.872,
  "cat": "historic",
  "region": "Peel Region",
  "approx": false,
  "blurb": "Pinjarra's restored heritage precinct — a homestead, gardens, tearooms and craft shops beside the Murray.",
  "hl": [
   "Historic Edenvale homestead",
   "Tearooms & craft shops",
   "Riverside gardens"
  ],
  "tip": "Free grounds; tearooms open most days."
 },
 {
  "slug": "koala-centre",
  "name": "Cohunu Koala Park",
  "lat": -32.22,
  "lon": 116.02,
  "cat": "attraction",
  "region": "Perth Hills",
  "approx": true,
  "blurb": "A wildlife park near Byford where you can hold a koala and meet kangaroos, deer and birds.",
  "hl": [
   "Hold a koala",
   "Miniature railway",
   "Hand-feed the animals"
  ],
  "tip": "Ticketed; koala holding at set times."
 },
 {
  "slug": "serpentine",
  "name": "Serpentine",
  "lat": -32.365,
  "lon": 115.98,
  "cat": "hills",
  "region": "Perth Hills",
  "approx": false,
  "blurb": "A small town below the Darling Scarp, gateway to Serpentine Falls, the dam and jarrah-forest trails.",
  "hl": [
   "Gateway to Serpentine Falls",
   "Serpentine Dam drive",
   "Country pub & shops"
  ],
  "tip": "Base for the national park and dam."
 },
 {
  "slug": "herdsman-lake",
  "name": "Herdsman Lake",
  "lat": -31.925,
  "lon": 115.805,
  "cat": "park",
  "region": "Nature",
  "approx": false,
  "blurb": "A large wetland reserve close to the city with a wildlife centre and a flat cycle/walk loop rich in birdlife.",
  "hl": [
   "Wildlife discovery centre",
   "Birdwatching hides",
   "Cycle & walk loop"
  ],
  "tip": "Free; excellent for birdwatchers."
 },
 {
  "slug": "bold-park",
  "name": "Bold Park",
  "lat": -31.945,
  "lon": 115.775,
  "cat": "park",
  "region": "Nature",
  "approx": false,
  "blurb": "A large natural bushland reserve near City Beach, with the Reabold Hill lookout over city and sea.",
  "hl": [
   "Reabold Hill lookout",
   "Bushland walk trails",
   "Spring wildflowers"
  ],
  "tip": "Free; highest natural point near the coast."
 },
 {
  "slug": "home",
  "name": "Home — 2 Zinnia Way, Willetton",
  "lat": -32.052,
  "lon": 115.89,
  "cat": "home",
  "region": "South of River",
  "approx": false,
  "blurb": "Home base for all the adventures — 2 Zinnia Way, Willetton, in Perth's leafy southern suburbs.",
  "hl": [
   "Start & end of every trip",
   "Willetton, south of the river",
   "Near the Canning River & Kwinana Fwy"
  ],
  "tip": "This is home! Plan your next outing from here."
 }
];
window.PERTH_CAT = {"park": "#2e8b57", "beach": "#1f78b4", "attraction": "#e69500", "hills": "#8B5A2B", "historic": "#7b3fa0", "food": "#c1121f", "suburb": "#5f6b7a", "home": "#e53935"};
window.PERTH_CATLABEL = {"park": "Parks & nature", "beach": "Beaches & water", "attraction": "Attractions", "hills": "Hills & towns", "historic": "Historic sites", "food": "Food, wine & brew", "suburb": "Suburbs & localities", "home": "Home"};
